// Browser checks against a running app. Outputs counts/booleans, never message text.
// Usage: node tests/browser_home.mjs http://127.0.0.1:8766 [output-directory]
import {spawn} from 'node:child_process';
import {existsSync, readFileSync, writeFileSync, mkdirSync} from 'node:fs';
import {setTimeout as delay} from 'node:timers/promises';
import path from 'node:path';
import assert from 'node:assert/strict';
import {checkScrape} from './browser_scrape.mjs';

const base = process.argv[2] || 'http://127.0.0.1:8766';
const output = path.resolve(process.argv[3] || 'agents/home-browser');
mkdirSync(output, {recursive:true});
const chrome = process.env.CHROME_PATH || path.join(process.env.ProgramFiles || '/opt', 'Google/Chrome/Application/chrome.exe');
assert(existsSync(chrome), 'Set CHROME_PATH to your Chromium browser executable');
const profile = path.join(output, `profile-${Date.now()}`);
const browser = spawn(chrome, ['--headless', '--disable-gpu', '--no-first-run', '--no-sandbox', '--remote-debugging-port=0', `--user-data-dir=${profile}`, 'about:blank'], {windowsHide:true, stdio:'ignore'});
const report = {checks:[], api:[]};
let socket;
try {
  const portFile = path.join(profile, 'DevToolsActivePort');
  for (let i=0; i<100 && !existsSync(portFile); i++) await delay(100);
  assert(existsSync(portFile), 'Browser debugging endpoint available');
  const port=Number(readFileSync(portFile,'utf8').split('\n')[0]);
  const targets=await (await fetch(`http://127.0.0.1:${port}/json/list`)).json();
  socket=new WebSocket(targets.find(t=>t.type==='page').webSocketDebuggerUrl);
  await new Promise((resolve,reject)=>{socket.onopen=resolve; socket.onerror=reject;});
  let id=0; const pending=new Map(); const exceptions=[];
  socket.onmessage=({data})=>{
    const msg=JSON.parse(data);
    if(msg.method==='Runtime.exceptionThrown') exceptions.push({description:msg.params.exceptionDetails.exception?.description || msg.params.exceptionDetails.text, line:msg.params.exceptionDetails.lineNumber});
    if(!msg.id) return;
    const item=pending.get(msg.id); pending.delete(msg.id);
    msg.error ? item.reject(msg.error) : item.resolve(msg.result);
  };
  const command=(method,params={})=>new Promise((resolve,reject)=>{const next=++id; pending.set(next,{resolve,reject}); socket.send(JSON.stringify({id:next,method,params}));});
  const evaluate=async expression=>{
    const r=await command('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true});
    assert(!r.exceptionDetails, 'Browser expression completed without exception');
    return r.result.value;
  };
  const until=async expression=>{for(let i=0;i<300;i++){if(await evaluate(expression))return; await delay(100);} throw new Error('Timed out: '+expression);};
  const navigate=async url=>{
    await evaluate(`window.__testNavigationPending=true`);
    const navigation=await command('Page.navigate',{url});
    // A hash-only CDP navigation keeps the old document and its test mocks.
    // Load through a blank document when the caller requests a fresh page.
    if (!navigation.loaderId) {
      await command('Page.navigate',{url:'about:blank'});
      await command('Page.navigate',{url});
    }
    await until(`!window.__testNavigationPending`);
  };
  const check=async(name,expr)=>{assert(await evaluate(expr), name);report.checks.push(name);};
  const click=async selector=>{
    await evaluate(`document.querySelector(${JSON.stringify(selector)}).scrollIntoView({behavior:'instant',block:'center'})`);
    await delay(650);
    const point=await evaluate(`(()=>{const r=document.querySelector(${JSON.stringify(selector)}).getBoundingClientRect();return {x:r.x+r.width/2,y:r.y+r.height/2};})()`);
    await command('Input.dispatchMouseEvent',{type:'mousePressed',button:'left',clickCount:1,...point});
    await command('Input.dispatchMouseEvent',{type:'mouseReleased',button:'left',clickCount:1,...point});
  };
  const key=async key=>{await command('Input.dispatchKeyEvent',{type:'keyDown',key});await command('Input.dispatchKeyEvent',{type:'keyUp',key});};
  const shot=async name=>{const r=await command('Page.captureScreenshot',{format:'png',captureBeyondViewport:true});writeFileSync(path.join(output,name+'.png'),Buffer.from(r.data,'base64'));};
  await command('Page.enable'); await command('Runtime.enable'); await command('Network.enable');
  // Real archived messages never leave this local test browser.
  await command('Network.setBlockedURLs',{urls:['https://*','http://cdn.*']});
  await command('Emulation.setDeviceMetricsOverride',{width:1440,height:1050,deviceScaleFactor:1,mobile:false});
  await navigate(base);
  await until(`document.body.dataset.archiveReady === 'true'`);
  await check('live archive totals', `Number(document.querySelector('#homeMessages').title.replaceAll(',',''))>0`);
  await check('settings stays closed without Discord', `!document.querySelector('#settingsPanel').classList.contains('open')`);
  await check('filters start inert', `document.querySelector('#filterTray').inert`);
  await shot('home-desktop');
  await click('#searchInput');
  await delay(650);
  await check('focus expands filters', `!document.querySelector('#filterTray').inert && document.querySelector('#searchInput').getAttribute('aria-expanded')==='true'`);
  await shot('home-desktop-expanded');
  await key('Escape');
  await check('Escape collapses filters', `document.querySelector('#filterTray').inert`);
  await click('#searchBtn');
  await until(`document.querySelectorAll('.result-row').length===50 && !document.querySelector('#searchResults').hasAttribute('aria-busy')`);
  await check('search reveals 50 real messages', `!document.querySelector('#resultsSection').hidden && !document.querySelector('#pagination').hidden`);
  await click('#pagination button:last-child');
  await until(`document.querySelector('.page-current')?.textContent==='page 2' && !document.querySelector('#searchResults').hasAttribute('aria-busy')`);
  await check('pagination updates URL', `new URLSearchParams(location.search).get('page')==='2'`);
  await evaluate(`(async()=>{window.fixture=await (await fetch('/api/search?limit=1')).json(); window.fixture=window.fixture.messages[0];})()`);
  await evaluate(`document.querySelector('#fGuild').value=window.fixture.guild_id||''; document.querySelector('#fChannel').value=window.fixture.channel_id; document.querySelector('#fUser').value=window.fixture.author_id; document.querySelector('#fDateFrom').value=window.fixture.timestamp.slice(0,10); document.querySelector('#fDateTo').value=window.fixture.timestamp.slice(0,10);`);
  await click('#searchBtn');
  await until(`!document.querySelector('#searchResults').hasAttribute('aria-busy') && document.querySelectorAll('.result-row').length>0`);
  await check('all ID and inclusive date filters in URL', `['channel_id','author_id','date_from','date_to'].every(k=>new URLSearchParams(location.search).has(k))`);
  await command('Page.reload');
  await until(`document.querySelectorAll('.result-row').length>0 && !document.querySelector('#searchResults').hasAttribute('aria-busy')`);
  await check('reload restores filters', `document.querySelector('#fChannel').value===new URLSearchParams(location.search).get('channel_id')`);
  await evaluate(`document.querySelector('#fGuild').value='nonexistent test server';`);
  await click('#searchBtn');
  await check('unknown filter rejected rather than broadened', `document.querySelector('#fGuild').getAttribute('aria-invalid')==='true' && document.querySelectorAll('.result-row').length===0`);
  await evaluate(`document.querySelector('#filterForm').reset();`);
  await until(`document.querySelectorAll('.result-row').length===50 && !document.querySelector('#searchResults').hasAttribute('aria-busy')`);
  await check('clear filters resets URL', `!new URLSearchParams(location.search).has('author_id')`);
  await evaluate(`document.querySelector('#searchInput').value='release';`);
  await click('#searchBtn');
  await until(`document.querySelectorAll('.result-row mark').length>0 && !document.querySelector('#searchResults').hasAttribute('aria-busy')`);
  await check('text query renders highlighted real matches', `[...document.querySelectorAll('.result-row .result-copy')].every(el=>el.textContent.toLowerCase().includes('release'))`);
  await evaluate(`document.querySelector('#searchInput').value=''; document.querySelector('#fGuild').value=document.querySelector('#dl-guilds option').value; document.querySelector('#fGuild').dispatchEvent(new Event('change',{bubbles:true}));`);
  await until(`!document.querySelector('#searchResults').hasAttribute('aria-busy')`);
  await check('server suggestion resolves to stable ID', `/^[0-9]+$/.test(new URLSearchParams(location.search).get('guild_id'))`);
  await evaluate(`document.querySelector('#fChannel').value=document.querySelector('#dl-channels option').value; document.querySelector('#fChannel').dispatchEvent(new Event('change',{bubbles:true}));`);
  await until(`!document.querySelector('#searchResults').hasAttribute('aria-busy')`);
  await check('channel suggestion resolves to stable ID', `/^[0-9]+$/.test(new URLSearchParams(location.search).get('channel_id'))`);
  await evaluate(`document.querySelector('#fUser').value='te'; document.querySelector('#fUser').dispatchEvent(new Event('input',{bubbles:true}));`);
  await until(`document.querySelectorAll('#dl-users option').length>0`);
  await check('author autocomplete is bounded', `document.querySelectorAll('#dl-users option').length<=20`);
  await evaluate(`document.querySelector('#filterForm').reset();`);
  await until(`document.querySelectorAll('.result-row').length===50 && !document.querySelector('#searchResults').hasAttribute('aria-busy')`);
  await evaluate(`document.querySelector('#searchInput').value='zzzz_home_e2e_no_match_zzzz';`);
  await click('#searchBtn');
  await until(`document.querySelector('#resultsStatus').textContent==='No messages match these filters'`);
  await check('empty results hide pagination', `document.querySelector('#pagination').hidden`);
  await evaluate(`document.querySelector('#searchInput').value=''; document.querySelector('#fDateFrom').value='2026-09-24'; document.querySelector('#fDateTo').value='2026-09-23';`);
  await click('#searchBtn');
  await check('reversed dates rejected', `document.querySelector('#fDateTo').getAttribute('aria-invalid')==='true'`);
  await click('#menuBtn');
  await check('settings opens with focused token input', `document.activeElement.id==='tokenInput' && !document.querySelector('#settingsPanel').inert`);
  await key('Escape');
  await check('settings Escape restores focus', `document.activeElement.id==='menuBtn' && document.querySelector('#settingsPanel').inert`);
  await check('three centered uniquely colored navigation boxes', `(()=>{const tabs=[...document.querySelectorAll('[data-view]')];return tabs.length===3 && tabs.every(el=>getComputedStyle(el).justifyContent==='center') && new Set(tabs.map(el=>getComputedStyle(el).getPropertyValue('--tab-accent').trim())).size===3;})()`);
  await click('[data-view="scrape"]');
  await until(`document.querySelector('#view-scrape').classList.contains('active')`);
  await check('unified scrape workspace', `document.querySelector('#homeOverview').hidden && !!document.querySelector('#view-scrape #liveMonitorList') && !!document.querySelector('#view-scrape #queueBar')`);
  await click('#sourceDms');
  await until(`document.querySelector('#dmBody .error-msg')`);
  await check('DM network failure is visible', `!!document.querySelector('#dmBody .error-msg')`);
  await click('[data-view="stats"]');
  await until(`Object.keys(_charts).length===6 && !document.querySelector('#view-stats').hasAttribute('aria-busy') && document.querySelectorAll('.lb-item').length===50`);
  await check('stats show real archive counts', `document.querySelector('#sTotal').title===document.querySelector('#homeMessages').title`);
  await check('six offline charts with accessible tables', `Object.values(_charts).every(c=>c.width>0) && document.querySelectorAll('.chart-data table').length===6 && [...document.scripts].some(s=>s.src.endsWith('/vendor/chart.umd.min.js'))`);
  await evaluate(`document.querySelector('#leaderboard').scrollTop=document.querySelector('#leaderboard').scrollHeight;`);
  await until(`document.querySelectorAll('.lb-item').length===100`);
  await check('contributors scroll into next page', `new Set([...document.querySelectorAll('.lb-uid')].map(el=>el.textContent)).size===100`);
  await click('#moreContributors');
  await until(`document.querySelectorAll('.lb-item').length===150`);
  await check('keyboard-accessible contributor pagination', `document.querySelectorAll('.lb-item').length===150`);
  await evaluate(`window.authorFixture=document.querySelector('.lb-uid').textContent;document.querySelector('#contributorSearch').value=window.authorFixture;document.querySelector('#contributorSearch').dispatchEvent(new Event('input',{bubbles:true}));`);
  await until(`!contributorState.busy && document.querySelectorAll('.lb-item').length===1`);
  await click('.lb-item');
  await until(`document.querySelector('#view-browse').classList.contains('active') && !document.querySelector('#searchResults').hasAttribute('aria-busy')`);
  await check('contributor drilldown searches real author', `new URLSearchParams(location.search).get('author_id')===window.authorFixture && document.querySelectorAll('.result-row').length>0`);
  await click('[data-view="stats"]');
  await until(`!document.querySelector('#view-stats').hasAttribute('aria-busy') && document.querySelector('#view-stats').classList.contains('active')`);
  await evaluate(`document.querySelector('#statsRange').value='7';document.querySelector('#statsRange').dispatchEvent(new Event('change'));`);
  await until(`!document.querySelector('#view-stats').hasAttribute('aria-busy') && _charts.chartOverTime.data.labels.length===7`);
  await evaluate(`document.querySelector('#timelineType').value='bar';document.querySelector('#timelineType').dispatchEvent(new Event('change'));document.querySelector('#serverChartType').value='doughnut';document.querySelector('#serverChartType').dispatchEvent(new Event('change'));`);
  await check('interactive timeline window and chart styles', `_charts.chartOverTime.config.type==='bar' && _charts.chartByServer.config.type==='doughnut'`);
  await evaluate(`document.querySelector('#chartByChannel').scrollIntoView({behavior:'instant',block:'center'});`);
  await delay(400);
  const chartPoint = await evaluate(`(()=>{const c=_charts.chartByChannel,r=c.canvas.getBoundingClientRect(),p=c.getDatasetMeta(0).data[0].getCenterPoint();return {x:r.x+p.x,y:r.y+p.y};})()`);
  await command('Input.dispatchMouseEvent',{type:'mouseMoved',...chartPoint});
  await delay(300);
  await check('chart hover exposes a tooltip', `_charts.chartByChannel.tooltip.opacity>0`);
  await command('Input.dispatchMouseEvent',{type:'mousePressed',button:'left',clickCount:1,...chartPoint});
  await command('Input.dispatchMouseEvent',{type:'mouseReleased',button:'left',clickCount:1,...chartPoint});
  await until(`activeView==='browse' && !document.querySelector('#searchResults').hasAttribute('aria-busy')`);
  await check('canvas selection searches the chosen channel', `new URLSearchParams(location.search).get('channel_id')===statsData.messages_by_channel[0].channel_id && document.querySelectorAll('.result-row').length>0`);
  await click('[data-view="stats"]');
  await until(`activeView==='stats' && !document.querySelector('#view-stats').hasAttribute('aria-busy')`);
  await evaluate(`document.querySelector('#statsRange').value='0';document.querySelector('#statsRange').dispatchEvent(new Event('change'));`);
  await until(`!document.querySelector('#view-stats').hasAttribute('aria-busy') && _charts.chartOverTime.data.labels.length>90`);
  await check('all-time timeline retains complete archive range', `_charts.chartOverTime.data.labels[0]===statsData.range_start && _charts.chartOverTime.data.labels.at(-1)===statsData.range_end`);
  await shot('stats-desktop');
  await evaluate(`document.querySelector('#chartByMonthData').parentElement.open=true;`);
  await click('#chartByMonthData button:last-of-type');
  await until(`document.querySelector('#view-browse').classList.contains('active') && !document.querySelector('#searchResults').hasAttribute('aria-busy')`);
  await check('chart table drilldown filters inclusive month', `new URLSearchParams(location.search).get('date_from')?.endsWith('-01') && !!new URLSearchParams(location.search).get('date_to') && document.querySelectorAll('.result-row').length>0`);
  await evaluate(`Promise.all([switchView('stats'),switchView('scrape'),switchView('browse')])`);
  await check('rapid navigation keeps final intended view', `activeView==='browse' && document.querySelectorAll('.view.active').length===1 && location.hash==='#browse'`);
  await evaluate(`(async()=>{const native=document.startViewTransition;document.startViewTransition=undefined;await switchView('scrape');await Promise.all([switchView('stats'),switchView('browse')]);document.startViewTransition=native;})()`);
  await delay(300);
  await check('fallback transitions settle without hidden content', `activeView==='browse' && getComputedStyle(document.querySelector('#pageStage')).opacity==='1'`);
  for(const width of [768,375]) {
    await command('Emulation.setDeviceMetricsOverride',{width,height:950,deviceScaleFactor:1,mobile:width<600});
    await navigate(base);
    await until(`document.body.dataset.archiveReady==='true'`);
    await check(`home has no horizontal overflow at ${width}`, `document.documentElement.scrollWidth<=innerWidth`);
    await shot(`home-${width}`);
    await click('#searchInput'); await delay(650);
    await check(`expanded filters fit at ${width}`, `document.documentElement.scrollWidth<=innerWidth && document.querySelector('#filterForm').getBoundingClientRect().bottom<=document.querySelector('#filterTray').getBoundingClientRect().bottom+1`);
    await shot(`home-${width}-expanded`);
    await key('Escape');
    await check(`totals fill two equal halves at ${width}`, `(()=>{const row=document.querySelector('.index-block'), panels=[...row.children],r=row.getBoundingClientRect(),a=panels[0].getBoundingClientRect(),b=panels[1].getBoundingClientRect();return Math.abs(a.width-b.width)<1 && Math.abs(a.left-r.left)<2 && Math.abs(b.right-r.right)<2;})()`);
    await evaluate(`document.querySelector('#homeMessages').textContent='9,999,999,999,999';document.querySelector('#homeServers').textContent='9,999,999,999';`);
    await delay(300);
    await check(`large archive counts fit at ${width}`, `[...document.querySelectorAll('.index-number')].every(el=>el.scrollWidth<=el.parentElement.clientWidth-2*parseFloat(getComputedStyle(el.parentElement).paddingLeft)+2)`);
    for (const view of ['scrape','stats']) {
      await click('[data-view="'+view+'"]');
      await until(`activeView==='${view}'`);
      if(view==='stats') await until(`Object.keys(_charts).length===6 && !document.querySelector('#view-stats').hasAttribute('aria-busy')`);
      await delay(400);
      await check(`${view} has no horizontal overflow at ${width}`, `document.documentElement.scrollWidth<=innerWidth`);
      await shot(`${view}-${width}`);
    }
  }
  await command('Emulation.setEmulatedMedia',{features:[{name:'prefers-reduced-motion',value:'reduce'}]});
  await check('reduced motion honored', `parseFloat(getComputedStyle(document.querySelector('.geometry-forms-right')).transitionDuration)<0.01`);
  await evaluate(`switchView('scrape')`);
  await check('reduced motion skips page transitions', `activeView==='scrape' && document.getAnimations().every(a=>!a.effect?.pseudoElement?.includes('view-transition'))`);
  // HTTP measurements use the same browser fetch path. Only aggregate values leave the page.
  report.api=await evaluate(`(async()=>{const out=[];for(const endpoint of ['/api/search?limit=50','/api/search?limit=50&page=2','/api/search?q=release&limit=50','/api/search/filters?include_users=false','/api/search/authors?q=te','/api/stats','/api/stats?days=0','/api/stats/contributors?offset=50&limit=50']){const start=performance.now();const r=await fetch(endpoint);const data=await r.json();out.push({endpoint,status:r.status,milliseconds:Math.round(performance.now()-start),rows:data.messages?.length??data.users?.length??data.length??null,total:data.total??data.total_messages??null});}return out;})()`);
  assert(report.api.every(r=>r.status===200), 'Read endpoints return success');
  await command('Emulation.setDeviceMetricsOverride',{width:1440,height:1050,deviceScaleFactor:1,mobile:false});
  await checkScrape({evaluate,check,click,until,key,shot});
  await command('Network.setCacheDisabled',{cacheDisabled:true});
  await command('Network.setBlockedURLs',{urls:['https://*','http://cdn.*',base+'/vendor/chart.umd.min.js']});
  await navigate(base+'/#stats');
  await until(`document.body.dataset.archiveReady==='true' && document.querySelectorAll('.chart-data table').length===6 && !document.querySelector('#view-stats').hasAttribute('aria-busy')`);
  await check('missing chart script preserves accessible data and totals', `typeof Chart==='undefined' && document.querySelectorAll('.chart-data[open]').length===6 && Number(document.querySelector('#sTotal').title.replaceAll(',',''))>0 && document.querySelector('#statsStatus').textContent.includes('data tables')`);
  if(exceptions.length) writeFileSync(path.join(output,'exceptions.json'),JSON.stringify(exceptions,null,2));
  assert.equal(exceptions.length,0,'No uncaught browser exceptions; details are in the ignored output folder');
  report.checks.push('no uncaught browser exceptions');
  writeFileSync(path.join(output,'report.json'),JSON.stringify(report,null,2));
  console.log(JSON.stringify(report,null,2));
} finally {socket?.close();browser.kill();}
