// Browser checks against a running app. Outputs counts/booleans, never message text.
// Usage: node tests/browser_home.mjs http://127.0.0.1:8766 [output-directory]
import {spawn} from 'node:child_process';
import {existsSync, readFileSync, writeFileSync, mkdirSync} from 'node:fs';
import {setTimeout as delay} from 'node:timers/promises';
import path from 'node:path';
import assert from 'node:assert/strict';

const base = process.argv[2] || 'http://127.0.0.1:8766';
const output = path.resolve(process.argv[3] || 'agents/home-browser');
mkdirSync(output, {recursive:true});
const chrome = process.env.CHROME_PATH || path.join(process.env.ProgramFiles || '/opt', 'Google/Chrome/Application/chrome.exe');
assert(existsSync(chrome), 'Set CHROME_PATH to your Chromium browser executable');
const profile = path.join(output, `profile-${Date.now()}`);
const browser = spawn(chrome, ['--headless', '--disable-gpu', '--no-first-run', '--no-sandbox', '--remote-debugging-port=0', `--user-data-dir=${profile}`, 'about:blank'], {windowsHide:true, stdio:'ignore'});
const report = {checks:[], api:[]};
let socket;
try {
  const portFile = path.join(profile, 'DevToolsActivePort');
  for (let i=0; i<100 && !existsSync(portFile); i++) await delay(100);
  assert(existsSync(portFile), 'Browser debugging endpoint available');
  const port=Number(readFileSync(portFile,'utf8').split('\n')[0]);
  const targets=await (await fetch(`http://127.0.0.1:${port}/json/list`)).json();
  socket=new WebSocket(targets.find(t=>t.type==='page').webSocketDebuggerUrl);
  await new Promise((resolve,reject)=>{socket.onopen=resolve; socket.onerror=reject;});
  let id=0; const pending=new Map(); const exceptions=[];
  socket.onmessage=({data})=>{
    const msg=JSON.parse(data);
    if(msg.method==='Runtime.exceptionThrown') exceptions.push(msg.params.exceptionDetails.text);
    if(!msg.id) return;
    const item=pending.get(msg.id); pending.delete(msg.id);
    msg.error ? item.reject(msg.error) : item.resolve(msg.result);
  };
  const command=(method,params={})=>new Promise((resolve,reject)=>{const next=++id; pending.set(next,{resolve,reject}); socket.send(JSON.stringify({id:next,method,params}));});
  const evaluate=async expression=>{
    const r=await command('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true});
    assert(!r.exceptionDetails, 'Browser expression completed without exception');
    return r.result.value;
  };
  const until=async expression=>{for(let i=0;i<300;i++){if(await evaluate(expression))return; await delay(100);} throw new Error('Timed out: '+expression);};
  const check=async(name,expr)=>{assert(await evaluate(expr), name);report.checks.push(name);};
  const click=async selector=>{
    await evaluate(`document.querySelector(${JSON.stringify(selector)}).scrollIntoView({behavior:'instant',block:'center'})`);
    await delay(650);
    const point=await evaluate(`(()=>{const r=document.querySelector(${JSON.stringify(selector)}).getBoundingClientRect();return {x:r.x+r.width/2,y:r.y+r.height/2};})()`);
    await command('Input.dispatchMouseEvent',{type:'mousePressed',button:'left',clickCount:1,...point});
    await command('Input.dispatchMouseEvent',{type:'mouseReleased',button:'left',clickCount:1,...point});
  };
  const key=async key=>{await command('Input.dispatchKeyEvent',{type:'keyDown',key});await command('Input.dispatchKeyEvent',{type:'keyUp',key});};
  const shot=async name=>{const r=await command('Page.captureScreenshot',{format:'png',captureBeyondViewport:true});writeFileSync(path.join(output,name+'.png'),Buffer.from(r.data,'base64'));};
  await command('Page.enable'); await command('Runtime.enable'); await command('Network.enable');
  // Real archived messages never leave this local test browser.
  await command('Network.setBlockedURLs',{urls:['https://*','http://cdn.*']});
  await command('Emulation.setDeviceMetricsOverride',{width:1440,height:1050,deviceScaleFactor:1,mobile:false});
  await command('Page.navigate',{url:base});
  await until(`document.querySelector('#connectionStatus')?.textContent === 'Local archive ready'`);
  await check('live archive totals', `Number(document.querySelector('#homeMessages').title.replaceAll(',',''))>0`);
  await check('settings stays closed without Discord', `!document.querySelector('#settingsPanel').classList.contains('open')`);
  await check('filters start inert', `document.querySelector('#filterTray').inert`);
  await shot('home-desktop');
  await click('#searchInput');
  await delay(650);
  await check('focus expands filters', `!document.querySelector('#filterTray').inert && document.querySelector('#searchInput').getAttribute('aria-expanded')==='true'`);
  await shot('home-desktop-expanded');
  await key('Escape');
  await check('Escape collapses filters', `document.querySelector('#filterTray').inert`);
  await click('#searchBtn');
  await until(`document.querySelectorAll('.result-row').length===50 && !document.querySelector('#searchResults').hasAttribute('aria-busy')`);
  await check('search reveals 50 real messages', `!document.querySelector('#resultsSection').hidden && !document.querySelector('#pagination').hidden`);
  await click('#pagination button:last-child');
  await until(`document.querySelector('.page-current')?.textContent==='page 2' && !document.querySelector('#searchResults').hasAttribute('aria-busy')`);
  await check('pagination updates URL', `new URLSearchParams(location.search).get('page')==='2'`);
  await evaluate(`(async()=>{window.fixture=await (await fetch('/api/search?limit=1')).json(); window.fixture=window.fixture.messages[0];})()`);
  await evaluate(`document.querySelector('#fGuild').value=window.fixture.guild_id||''; document.querySelector('#fChannel').value=window.fixture.channel_id; document.querySelector('#fUser').value=window.fixture.author_id; document.querySelector('#fDateFrom').value=window.fixture.timestamp.slice(0,10); document.querySelector('#fDateTo').value=window.fixture.timestamp.slice(0,10);`);
  await click('#searchBtn');
  await until(`!document.querySelector('#searchResults').hasAttribute('aria-busy') && document.querySelectorAll('.result-row').length>0`);
  await check('all ID and inclusive date filters in URL', `['channel_id','author_id','date_from','date_to'].every(k=>new URLSearchParams(location.search).has(k))`);
  await command('Page.reload');
  await until(`document.querySelectorAll('.result-row').length>0 && !document.querySelector('#searchResults').hasAttribute('aria-busy')`);
  await check('reload restores filters', `document.querySelector('#fChannel').value===new URLSearchParams(location.search).get('channel_id')`);
  await evaluate(`document.querySelector('#fGuild').value='nonexistent test server';`);
  await click('#searchBtn');
  await check('unknown filter rejected rather than broadened', `document.querySelector('#fGuild').getAttribute('aria-invalid')==='true' && document.querySelectorAll('.result-row').length===0`);
  await evaluate(`document.querySelector('#filterForm').reset();`);
  await until(`document.querySelectorAll('.result-row').length===50 && !document.querySelector('#searchResults').hasAttribute('aria-busy')`);
  await check('clear filters resets URL', `!new URLSearchParams(location.search).has('author_id')`);
  await evaluate(`document.querySelector('#searchInput').value='release';`);
  await click('#searchBtn');
  await until(`document.querySelectorAll('.result-row mark').length>0 && !document.querySelector('#searchResults').hasAttribute('aria-busy')`);
  await check('text query renders highlighted real matches', `[...document.querySelectorAll('.result-row .result-copy')].every(el=>el.textContent.toLowerCase().includes('release'))`);
  await evaluate(`document.querySelector('#searchInput').value=''; document.querySelector('#fGuild').value=document.querySelector('#dl-guilds option').value; document.querySelector('#fGuild').dispatchEvent(new Event('change',{bubbles:true}));`);
  await until(`!document.querySelector('#searchResults').hasAttribute('aria-busy')`);
  await check('server suggestion resolves to stable ID', `/^[0-9]+$/.test(new URLSearchParams(location.search).get('guild_id'))`);
  await evaluate(`document.querySelector('#fChannel').value=document.querySelector('#dl-channels option').value; document.querySelector('#fChannel').dispatchEvent(new Event('change',{bubbles:true}));`);
  await until(`!document.querySelector('#searchResults').hasAttribute('aria-busy')`);
  await check('channel suggestion resolves to stable ID', `/^[0-9]+$/.test(new URLSearchParams(location.search).get('channel_id'))`);
  await evaluate(`document.querySelector('#fUser').value='te'; document.querySelector('#fUser').dispatchEvent(new Event('input',{bubbles:true}));`);
  await until(`document.querySelectorAll('#dl-users option').length>0`);
  await check('author autocomplete is bounded', `document.querySelectorAll('#dl-users option').length<=20`);
  await evaluate(`document.querySelector('#filterForm').reset();`);
  await until(`document.querySelectorAll('.result-row').length===50 && !document.querySelector('#searchResults').hasAttribute('aria-busy')`);
  await evaluate(`document.querySelector('#searchInput').value='zzzz_home_e2e_no_match_zzzz';`);
  await click('#searchBtn');
  await until(`document.querySelector('#resultsStatus').textContent==='No messages match these filters'`);
  await check('empty results hide pagination', `document.querySelector('#pagination').hidden`);
  await evaluate(`document.querySelector('#searchInput').value=''; document.querySelector('#fDateFrom').value='2026-09-24'; document.querySelector('#fDateTo').value='2026-09-23';`);
  await click('#searchBtn');
  await check('reversed dates rejected', `document.querySelector('#fDateTo').getAttribute('aria-invalid')==='true'`);
  await click('#menuBtn');
  await check('settings opens with focused token input', `document.activeElement.id==='tokenInput' && !document.querySelector('#settingsPanel').inert`);
  await key('Escape');
  await check('settings Escape restores focus', `document.activeElement.id==='menuBtn' && document.querySelector('#settingsPanel').inert`);
  await click('[data-view="live"]');
  await check('live navigation', `document.querySelector('#view-live').classList.contains('active') && document.querySelector('#homeOverview').hidden`);
  await click('[data-view="dms"]');
  await until(`document.querySelector('#dmBody .error-msg')`);
  await check('DM network failure is visible', `!!document.querySelector('#dmBody .error-msg')`);
  await click('[data-view="stats"]');
  await until(`document.querySelector('#sTotal').textContent!=='—'`);
  await check('stats show real archive counts', `document.querySelector('#sTotal').textContent===document.querySelector('#homeMessages').title`);
  await check('offline chart dependency has a visible fallback', `document.querySelectorAll('.chart-error').length===3`);
  for(const width of [768,375]) {
    await command('Emulation.setDeviceMetricsOverride',{width,height:950,deviceScaleFactor:1,mobile:width<600});
    await command('Page.navigate',{url:base});
    await until(`document.querySelector('#connectionStatus')?.textContent==='Local archive ready'`);
    await check(`home has no horizontal overflow at ${width}`, `document.documentElement.scrollWidth<=innerWidth`);
    await shot(`home-${width}`);
    await click('#searchInput'); await delay(650);
    await check(`expanded filters fit at ${width}`, `document.documentElement.scrollWidth<=innerWidth && document.querySelector('#filterForm').getBoundingClientRect().bottom<=document.querySelector('#filterTray').getBoundingClientRect().bottom+1`);
    await shot(`home-${width}-expanded`);
  }
  await command('Emulation.setEmulatedMedia',{features:[{name:'prefers-reduced-motion',value:'reduce'}]});
  await check('reduced motion honored', `parseFloat(getComputedStyle(document.querySelector('.geometry-forms-right')).transitionDuration)<0.01`);
  // HTTP measurements use the same browser fetch path. Only aggregate values leave the page.
  report.api=await evaluate(`(async()=>{const out=[];for(const endpoint of ['/api/search?limit=50','/api/search?limit=50&page=2','/api/search?q=release&limit=50','/api/search/filters?include_users=false','/api/search/authors?q=te','/api/stats']){const start=performance.now();const r=await fetch(endpoint);const data=await r.json();out.push({endpoint,status:r.status,milliseconds:Math.round(performance.now()-start),rows:data.messages?.length??data.length??null,total:data.total??data.total_messages??null});}return out;})()`);
  assert(report.api.every(r=>r.status===200), 'Read endpoints return success');
  assert.equal(exceptions.length,0,'No uncaught browser exceptions');
  report.checks.push('no uncaught browser exceptions');
  writeFileSync(path.join(output,'report.json'),JSON.stringify(report,null,2));
  console.log(JSON.stringify(report,null,2));
} finally {socket?.close();browser.kill();}
