// Local Chrome checks. Prints assertions and timings, never archived text.
// node checks/browser_search.mjs http://127.0.0.1:8001 agents/search-browser
import {spawn} from 'node:child_process';
import {existsSync, readFileSync, writeFileSync, mkdirSync} from 'node:fs';
import {setTimeout as delay} from 'node:timers/promises';
import path from 'node:path';
import assert from 'node:assert/strict';

const base = process.argv[2] || 'http://127.0.0.1:8001';
const output = path.resolve(process.argv[3] || 'agents/search-browser');
mkdirSync(output,{recursive:true});
const chrome = process.env.CHROME_PATH || path.join(process.env.ProgramFiles,'Google/Chrome/Application/chrome.exe');
const profile = path.join(output,`profile-${Date.now()}`);
const browser = spawn(chrome,['--headless','--disable-gpu','--no-first-run','--no-sandbox','--remote-debugging-port=0',`--user-data-dir=${profile}`,'about:blank'],{windowsHide:true,stdio:'ignore'});
let socket;
const report = {checks:[],timings:{}};
try {
  const portFile=path.join(profile,'DevToolsActivePort');
  for(let i=0;i<100&&!existsSync(portFile);i++) await delay(100);
  assert(existsSync(portFile),'Chrome debugging port available');
  const port=Number(readFileSync(portFile,'utf8').split('\n')[0]);
  const targets=await(await fetch(`http://127.0.0.1:${port}/json/list`)).json();
  socket=new WebSocket(targets.find(t=>t.type==='page').webSocketDebuggerUrl);
  await new Promise((resolve,reject)=>{socket.onopen=resolve;socket.onerror=reject;});
  let id=0;const pending=new Map();const exceptions=[];const requests=[];
  socket.onmessage=({data})=>{
    const msg=JSON.parse(data);
    if(msg.method==='Runtime.exceptionThrown') exceptions.push(msg.params.exceptionDetails.text);
    if(msg.method==='Network.requestWillBeSent') requests.push(msg.params.request.url);
    if(!msg.id)return;
    const item=pending.get(msg.id);pending.delete(msg.id);
    msg.error?item.reject(msg.error):item.resolve(msg.result);
  };
  const command=(method,params={})=>new Promise((resolve,reject)=>{const next=++id;pending.set(next,{resolve,reject});socket.send(JSON.stringify({id:next,method,params}));});
  const evaluate=async expression=>{const r=await command('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true});assert(!r.exceptionDetails,JSON.stringify(r.exceptionDetails));return r.result.value;};
  const until=async expression=>{for(let i=0;i<150;i++){if(await evaluate(expression))return;await delay(100);}throw new Error('Timed out: '+expression);};
  const check=async(name,expression)=>{assert(await evaluate(expression),name);report.checks.push(name);};
  const key=async key=>{await command('Input.dispatchKeyEvent',{type:'keyDown',key});await command('Input.dispatchKeyEvent',{type:'keyUp',key});};
  const click=async selector=>{
    await evaluate(`document.querySelector(${JSON.stringify(selector)}).scrollIntoView({behavior:'instant',block:'center'})`);
    const point=await evaluate(`(()=>{const r=document.querySelector(${JSON.stringify(selector)}).getBoundingClientRect();return {x:r.x+r.width/2,y:r.y+r.height/2};})()`);
    await command('Input.dispatchMouseEvent',{type:'mousePressed',button:'left',clickCount:1,...point});
    await command('Input.dispatchMouseEvent',{type:'mouseReleased',button:'left',clickCount:1,...point});
  };
  const screenshot=async name=>{await delay(220);const r=await command('Page.captureScreenshot',{format:'png',captureBeyondViewport:false});writeFileSync(path.join(output,name+'.png'),Buffer.from(r.data,'base64'));};
  const settled=`document.querySelector('#resultBody').getAttribute('aria-busy')==='false' && !document.querySelector('#results').hidden`;
  await command('Page.enable');await command('Runtime.enable');await command('Network.enable');
  await command('Emulation.setDeviceMetricsOverride',{width:1440,height:1000,deviceScaleFactor:1,mobile:false});
  await command('Page.navigate',{url:base});
  await until(`document.body?.dataset.archiveReady==='true'`);
  await screenshot('desktop-home');
  report.timings.load=await evaluate(`(()=>{const n=performance.getEntriesByType('navigation')[0];return {dom_ms:Math.round(n.domContentLoadedEventEnd),load_ms:Math.round(n.loadEventEnd),resources:performance.getEntriesByType('resource').length}})()`);
  await check('one search surface, no workspace tabs',`document.querySelectorAll('[role=search]').length===1 && !document.querySelector('.surface-tabs')`);
  await check('hero text preserved',`document.querySelector('h1').textContent==='searchcord' && document.querySelector('h2').textContent==='What are youlooking for?'`);
  await check('requested decorative copy removed',`!document.body.innerText.includes('Search your messages') && !document.body.innerText.includes('Your archive.') && !document.body.innerText.includes('Stored locally.') && !document.body.innerText.includes('3+ characters')`);
  await check('archive counters share the original box and type style',`(()=>{const boxes=[...document.querySelectorAll('.index-stat')], numbers=[...document.querySelectorAll('.index-number')]; return boxes.length===2 && boxes.every(e=>getComputedStyle(e).borderTopWidth==='1px') && numbers.every(e=>getComputedStyle(e).fontWeight==='800')})()`);
  await check('results hidden until search',`document.querySelector('#results').hidden`);
  await check('desktop has no overflow',`document.documentElement.scrollWidth===innerWidth`);
  await click('#searchInput');
  await check('focus opens filters',`!document.querySelector('#filterTray').inert`);
  await key('Escape');
  await check('Escape closes filters and keeps focus',`document.querySelector('#filterTray').inert && document.activeElement.id==='searchInput'`);
  await click('#searchInput');
  await check('click reopens filters after Escape',`!document.querySelector('#filterTray').inert`);
  await screenshot('desktop-filters');
  await click('.masthead');
  await check('outside click closes filters',`document.querySelector('#filterTray').inert`);
  await evaluate(`document.querySelector('#searchInput').value='hi';document.querySelector('#searchForm').requestSubmit()`);
  await until(settled);
  await check('short search remains supported',`document.querySelector('#searchError').hidden && document.querySelectorAll('.result-row').length>0`);
  await evaluate(`document.querySelector('#searchInput').value='hello';document.querySelector('#searchInput').dispatchEvent(new Event('input'));window.searchStart=performance.now();document.querySelector('#searchForm').requestSubmit()`);
  await until(settled);
  report.timings.search_dom_ms=await evaluate('Math.round(performance.now()-window.searchStart)');
  await check('real dataset returns bounded results',`document.querySelectorAll('.result-row').length>0 && document.querySelectorAll('.result-row').length<=50`);
  await check('literal match highlighting',`document.querySelector('mark')?.textContent.toLowerCase()==='hello'`);
  await check('technical results summary is absent',`!document.body.innerText.includes('more available') && !document.body.innerText.includes(' ms')`);
  await check('URL retains search',`new URLSearchParams(location.search).get('q')==='hello'`);
  await evaluate(`window.firstIds=[...document.querySelectorAll('.result-row')].map(e=>e.dataset.id)`);
  await click('#nextPage');await until(settled);
  await check('next page cursor has no duplicate messages',`document.querySelector('#pageNumber').textContent==='Page 2' && [...document.querySelectorAll('.result-row')].every(e=>!window.firstIds.includes(e.dataset.id))`);
  await click('#previousPage');await until(settled);
  await check('previous restores first page',`JSON.stringify([...document.querySelectorAll('.result-row')].map(e=>e.dataset.id))===JSON.stringify(window.firstIds)`);
  await evaluate('history.back()');await until(`document.querySelector('#pageNumber').textContent==='Page 2' && ${settled}`);
  await check('browser back restores cursor page',`new URLSearchParams(location.search).has('before')`);
  await command('Page.reload');await until(`document.body?.dataset.archiveReady==='true' && ${settled}`);
  await check('reload restores cursor and page',`document.querySelector('#pageNumber').textContent==='Page 2'`);
  await evaluate(`document.querySelector('#searchInput').value='zzzzunlikelymatch';document.querySelector('#searchForm').requestSubmit()`);await until(settled);
  await check('empty state gives edit action',`!document.querySelector('#emptyState').hidden && document.querySelector('#pagination').hidden`);
  await screenshot('desktop-empty');
  await evaluate(`document.querySelector('#searchInput').value='';document.querySelector('#searchForm').requestSubmit()`);await until(settled);
  await check('empty query browses archive',`document.querySelectorAll('.result-row').length===50`);
  // Synthetic responses exercise hostile text, long messages and request races.
  await evaluate(`window.realFetch=window.fetch;window.fetch=async(url,options)=>String(url).startsWith('/api/search?')?new Response(JSON.stringify({messages:[{id:'1',author_id:'1',author_name:'Synthetic user',timestamp:'2026-09-01T10:30:00Z',guild_name:'Test server',channel_name:'general',content:'<img src=x onerror=alert(1)> '+ 'long message '.repeat(250),attachments:[]}],has_more:false,next_cursor:null,elapsed_ms:2}),{headers:{'content-type':'application/json'}}):window.realFetch(url,options);document.querySelector('#searchInput').value='long';document.querySelector('#searchForm').requestSubmit()`);await until(settled);
  await check('archived HTML stays inert',`!document.querySelector('.result-copy img') && document.querySelector('.result-copy').textContent.includes('<img')`);
  await check('full messages are shown without disclosure',`document.querySelector('.result-copy').textContent.length>2000 && !document.querySelector('.expand-message')`);
  await check('original message metadata stays in the heading',`document.querySelector('.message-heading .message-author') && document.querySelector('.message-heading .message-time') && document.querySelector('.message-heading .message-location') && document.querySelector('.message-heading .message-id')`);
  await check('message rows have no list numbering',`document.querySelector('.result-row').tagName==='ARTICLE' && !document.querySelector('#messages li')`);
  await screenshot('desktop-results-synthetic');
  await evaluate(`window.fetch=async(url,options)=>{if(!String(url).startsWith('/api/search?'))return window.realFetch(url,options);const q=new URLSearchParams(String(url).split('?')[1]).get('q');await new Promise(r=>setTimeout(r,q==='older'?350:20));return new Response(JSON.stringify({messages:[],has_more:false,next_cursor:null,elapsed_ms:q==='older'?999:2}),{headers:{'content-type':'application/json'}})};document.querySelector('#searchInput').value='older';document.querySelector('#searchForm').requestSubmit();document.querySelector('#searchInput').value='newer';document.querySelector('#searchForm').requestSubmit()`);
  await delay(500);
  await check('stale response cannot overwrite newer search',`new URLSearchParams(location.search).get('q')==='newer' && document.querySelector('#resultStatus').textContent==='No messages match these filters.'`);
  await evaluate(`window.fetch=async()=>{throw new Error('Synthetic offline failure')};document.querySelector('#searchForm').requestSubmit()`);await until(settled);
  await check('network error clears stale results and stays actionable',`!document.querySelector('#searchError').hidden && document.querySelectorAll('.result-row').length===0 && document.querySelector('#pagination').hidden`);
  await evaluate('window.fetch=window.realFetch');
  await command('Emulation.setEmulatedMedia',{features:[{name:'prefers-reduced-motion',value:'reduce'}]});
  await click('#searchInput');
  await check('reduced motion disables tray transitions',`getComputedStyle(document.querySelector('#filterTray')).transitionDuration==='0s'`);
  for(const width of [390,320]){
    await command('Emulation.setDeviceMetricsOverride',{width,height:844,deviceScaleFactor:1,mobile:true});
    await command('Page.navigate',{url:base});await until(`document.body?.dataset.archiveReady==='true'`);
    await check(`mobile ${width} no horizontal overflow`,`document.documentElement.scrollWidth===innerWidth`);
    await check(`mobile ${width} search button fits its label`,`(()=>{const b=document.querySelector('.query-form button');return b.scrollWidth<=b.clientWidth})()`);
    await screenshot(`mobile-${width}-home`);
    await click('#searchInput');
    await check(`mobile ${width} filters no horizontal overflow`,`document.documentElement.scrollWidth===innerWidth`);
    await screenshot(`mobile-${width}-filters`);
    await evaluate(`document.querySelector('#searchForm').requestSubmit()`);await until(settled);
    await check(`mobile ${width} results no horizontal overflow`,`document.documentElement.scrollWidth===innerWidth`);
  }
  await command('Emulation.setDeviceMetricsOverride',{width:1440,height:1000,deviceScaleFactor:1,mobile:false});
  await command('Page.navigate',{url:base}); await until(`document.body?.dataset.archiveReady==='true'`);
  await click('#searchInput');
  await evaluate(`document.querySelector('#dateFrom').value='2027-01-01';document.querySelector('#dateTo').value='2027-01-02';document.querySelector('#dateTo').dispatchEvent(new Event('change'))`);
  await until(settled);
  await check('changing a filter searches immediately',`new URLSearchParams(location.search).get('date_to')==='2027-01-02' && !document.querySelector('#emptyState').hidden`);
  await click('#clearFilters'); await until(settled);
  await check('clear filters immediately restores results',`!new URLSearchParams(location.search).has('date_to') && document.querySelectorAll('.result-row').length===50`);
  await click('.site-footer a'); await until(`!!document.querySelector('#privacyTitle')`);
  await check('existing privacy page moved to display frontend',`document.querySelector('#privacyTitle').textContent==='privacy & data' && document.querySelector('.privacy-footer a').getAttribute('href')==='index.html'`);
  await screenshot('privacy');
  await click('.privacy-footer a'); await until(`document.body?.dataset.archiveReady==='true'`);
  await check('privacy return opens search frontend',`!!document.querySelector('#searchForm')`);
  assert.deepEqual(exceptions,[],'no uncaught browser errors');report.checks.push('no uncaught browser errors');
  assert(requests.every(url=>url.startsWith(base)||url==='about:blank'||url.startsWith('data:')||url.startsWith('https://cdn.discordapp.com/avatars/')),'only local assets and original avatar URLs');report.checks.push('only local assets and original avatar URLs');
  writeFileSync(path.join(output,'report.json'),JSON.stringify(report,null,2));
  console.log(JSON.stringify(report,null,2));
}finally{socket?.close();browser.kill();}
