// Local Chrome checks. Prints assertions and timings, never archived text.
// node checks/browser_profile_search.mjs http://127.0.0.1:8003 agents/profile-search-browser
import {spawn} from 'node:child_process';
import {existsSync, readFileSync, writeFileSync, mkdirSync} from 'node:fs';
import {setTimeout as delay} from 'node:timers/promises';
import path from 'node:path';
import assert from 'node:assert/strict';

const base = process.argv[2] || 'http://127.0.0.1:8003';
const output = path.resolve(process.argv[3] || 'agents/profile-search-browser');
mkdirSync(output,{recursive:true});
const chrome = process.env.CHROME_PATH || path.join(process.env.ProgramFiles,'Google/Chrome/Application/chrome.exe');
const profile = path.join(output,`profile-${Date.now()}`);
const browser = spawn(chrome,['--headless','--disable-gpu','--no-first-run','--no-sandbox','--remote-debugging-port=0',`--user-data-dir=${profile}`,'about:blank'],{windowsHide:true,stdio:'ignore'});
let socket;
const report = {checks:[],timings:{}};
try {
  const portFile=path.join(profile,'DevToolsActivePort');
  for(let i=0;i<100&&!existsSync(portFile);i++) await delay(100);
  assert(existsSync(portFile),'Chrome debugging port available');
  const port=Number(readFileSync(portFile,'utf8').split('\n')[0]);
  const targets=await(await fetch(`http://127.0.0.1:${port}/json/list`)).json();
  socket=new WebSocket(targets.find(t=>t.type==='page').webSocketDebuggerUrl);
  await new Promise((resolve,reject)=>{socket.onopen=resolve;socket.onerror=reject;});
  let id=0;const pending=new Map();const exceptions=[];const requests=[];
  socket.onmessage=({data})=>{
    const msg=JSON.parse(data);
    if(msg.method==='Runtime.exceptionThrown') exceptions.push(msg.params.exceptionDetails.text);
    if(msg.method==='Network.requestWillBeSent') requests.push(msg.params.request.url);
    if(!msg.id)return;
    const item=pending.get(msg.id);pending.delete(msg.id);
    msg.error?item.reject(msg.error):item.resolve(msg.result);
  };
  const command=(method,params={})=>new Promise((resolve,reject)=>{const next=++id;pending.set(next,{resolve,reject});socket.send(JSON.stringify({id:next,method,params}));});
  const evaluate=async expression=>{const r=await command('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true});assert(!r.exceptionDetails,JSON.stringify(r.exceptionDetails));return r.result.value;};
  const until=async expression=>{for(let i=0;i<150;i++){if(await evaluate(expression))return;await delay(100);}throw new Error('Timed out: '+expression);};
  const check=async(name,expression)=>{assert(await evaluate(expression),name);report.checks.push(name);};
  const key=async key=>{const windowsVirtualKeyCode=key==='Enter'?13:key==='Escape'?27:0;await command('Input.dispatchKeyEvent',{type:'keyDown',key,windowsVirtualKeyCode,...(key==='Enter'?{text:'\r'}:{})});await command('Input.dispatchKeyEvent',{type:'keyUp',key,windowsVirtualKeyCode});};
  const click=async selector=>{
    await evaluate(`document.querySelector(${JSON.stringify(selector)}).scrollIntoView({behavior:'instant',block:'center'})`);
    await delay(400);
    const point=await evaluate(`(()=>{const r=document.querySelector(${JSON.stringify(selector)}).getBoundingClientRect();return {x:r.x+r.width/2,y:r.y+r.height/2};})()`);
    await command('Input.dispatchMouseEvent',{type:'mousePressed',button:'left',clickCount:1,...point});
    await command('Input.dispatchMouseEvent',{type:'mouseReleased',button:'left',clickCount:1,...point});
  };
  const screenshot=async name=>{await delay(220);const r=await command('Page.captureScreenshot',{format:'png',captureBeyondViewport:false});writeFileSync(path.join(output,name+'.png'),Buffer.from(r.data,'base64'));};
  const settled=`document.querySelector('#resultBody').getAttribute('aria-busy')==='false' && !document.querySelector('#results').hidden`;
  await command('Page.enable');await command('Runtime.enable');await command('Network.enable');
  await command('Emulation.setDeviceMetricsOverride',{width:1440,height:1000,deviceScaleFactor:1,mobile:false});
  await command('Page.navigate',{url:base});
  await until(`document.body?.dataset.archiveReady==='true'`);
  await screenshot('desktop-home');
  report.timings.load=await evaluate(`(()=>{const n=performance.getEntriesByType('navigation')[0];return {dom_ms:Math.round(n.domContentLoadedEventEnd),load_ms:Math.round(n.loadEventEnd),resources:performance.getEntriesByType('resource').length}})()`);
  await click('#searchInput');
  await evaluate(`document.querySelector('#channel').value='general';document.querySelector('#channel').dispatchEvent(new Event('input'))`);
  await until(`document.querySelector('#channelOptions option')`);
  await check('emoji channel matches plain text',`document.querySelector('#channelOptions option').value==='#general-chat · 200'`);
  await evaluate(`document.querySelector('#channel').value=document.querySelector('#channelOptions option').value;document.querySelector('#channel').dispatchEvent(new Event('change'))`);
  await until(settled);
  await check('emoji channel selection searches by stable ID',`new URLSearchParams(location.search).get('channel_id')==='200' && document.querySelectorAll('.result-row').length===47`);
  await click('#searchInput');
  await evaluate(`document.querySelector('#searchInput').value='@alice';document.querySelector('#searchInput').dispatchEvent(new Event('input'))`);
  await until(`document.querySelector('#profileOptions option')`);
  await check('mention autofill matches saved username',`document.querySelector('#profileOptions option').value==='@alice.example · 50'`);
  await evaluate(`document.querySelector('#searchInput').value=document.querySelector('#profileOptions option').value;document.querySelector('#searchForm').requestSubmit()`);
  await until(`document.querySelector('.profile-name')?.textContent==='Alice Example' && ${settled}`);
  await check('mention opens branded profile with full archive results',`!document.querySelector('#profileSection').hidden && document.querySelectorAll('.result-row').length===50 && new URLSearchParams(location.search).get('profile')==='50' && !new URLSearchParams(location.search).has('channel_id')`);
  await check('profile navigation receives keyboard focus',`document.activeElement.id==='closeProfile'`);
  await check('profile search stays compact with no duplicate identity button',`!document.querySelector('#profileHost .profile-actions') && document.querySelector('#profileMessageForm').hidden`);
  await check('profile messages follow card in document order',`!!(document.querySelector('#profileSection').compareDocumentPosition(document.querySelector('#results')) & Node.DOCUMENT_POSITION_FOLLOWING)`);
  await check('messages ordered newest first',`(()=>{const ids=[...document.querySelectorAll('.result-row')].map(e=>BigInt(e.dataset.id));return ids.every((id,i)=>!i||ids[i-1]>id)})()`);
  await until(`document.querySelectorAll('.profile-server').length===30`);
  await screenshot('profile-desktop');
  await click('.profile-more');await until(`document.querySelectorAll('.profile-server').length===45`);
  await evaluate(`document.querySelector('.profile-server-search input').value='garden';document.querySelector('.profile-server-search input').dispatchEvent(new Event('input'))`);
  await until(`document.querySelectorAll('.profile-server').length===1`);
  await check('profile server search and paging work',`document.querySelector('.profile-server strong').textContent==='Garden Club'`);
  await click('#profileSearchToggle');
  await check('search icon opens and focuses the popout field',`!document.querySelector('#profileMessageForm').hidden && document.activeElement.id==='profileMessageQuery' && !document.querySelector('#profileMessageForm button')`);
  await key('Escape');
  await check('Escape closes search and returns focus',`document.querySelector('#profileMessageForm').hidden && document.activeElement.id==='profileSearchToggle'`);
  await click('#profileSearchToggle');
  await screenshot('profile-search-popout');
  await evaluate(`document.querySelector('#profileMessageQuery').value='not-present-fixture'`);await key('Enter');await until(settled);
  await check('profile message search scopes to current user',`new URLSearchParams(location.search).get('author_id')==='50' && !document.querySelector('#emptyState').hidden`);
  await click('#editSearch');
  await check('empty profile search focuses its own query',`document.activeElement.id==='profileMessageQuery'`);
  await command('Page.reload');await until(`document.querySelector('.profile-name')?.textContent==='Alice Example' && ${settled}`);
  await check('profile and message query restore after reload',`document.querySelector('#profileMessageQuery').value==='not-present-fixture' && !document.querySelector('#emptyState').hidden`);
  await evaluate('history.back()');await until(`document.querySelector('.profile-name')?.textContent==='Alice Example' && document.querySelectorAll('.result-row').length===50 && ${settled}`);
  await check('browser back restores profile results',`!new URLSearchParams(location.search).has('q')`);
  for(const width of [390,320]){
    await command('Emulation.setDeviceMetricsOverride',{width,height:844,deviceScaleFactor:1,mobile:true});
    await evaluate(`document.querySelector('#profileSection').scrollIntoView({behavior:'instant'})`);
    await screenshot('profile-mobile-'+width);
    await check('profile fits mobile '+width,`document.documentElement.scrollWidth===innerWidth`);
    await click('#profileSearchToggle');
    await check('search popout fits mobile '+width,`(()=>{const r=document.querySelector('#profileMessageForm').getBoundingClientRect();return r.left>=0 && r.right<=innerWidth && document.activeElement.id==='profileMessageQuery'})()`);
    await click('#resultsTitle');
    await check('outside click closes mobile popout '+width,`document.querySelector('#profileMessageForm').hidden`);
  }
  await click('#closeProfile');
  await check('back to search restores hero',`!document.body.classList.contains('has-profile') && !new URLSearchParams(location.search).has('profile')`);
  await evaluate(`document.querySelector('#searchInput').value='@60';document.querySelector('#searchForm').requestSubmit()`);
  await until(`document.querySelector('.profile-name')?.textContent==='Bob Example' && ${settled}`);
  await check('raw user ID opens unscraped identity',`document.querySelector('.profile-status').textContent.includes('not been scraped') && document.querySelectorAll('.result-row').length===1`);
  await check('display profile cannot trigger collection',`!document.querySelector('.profile-fetch')`);
  await click('#closeProfile');await evaluate(`document.querySelector('#searchInput').value='@alice.example';document.querySelector('#searchForm').requestSubmit()`);
  await until(`document.querySelector('.profile-name')?.textContent==='Alice Example' && ${settled}`);
  await check('typed exact username resolves without selecting suggestion',`new URLSearchParams(location.search).get('profile')==='50'`);
  // A local image fixture verifies the shared renderer without depending on CDN availability.
  await evaluate(`(async()=>{
    const data=await(await fetch('/api/profiles/50')).json();
    data.avatar_url=data.banner_url='data:image/svg+xml,'+encodeURIComponent('<svg xmlns="http://www.w3.org/2000/svg" width="32" height="32"><rect width="32" height="32" fill="%239bdcba"/></svg>');
    const host=document.createElement('div');host.id='imageFixture';document.body.append(host);
    new SearchcordProfile(host).render(data);
  })()`);
  await until(`document.querySelector('#imageFixture .profile-portrait img')?.naturalWidth===32 && document.querySelector('#imageFixture .profile-banner img')?.naturalWidth===32`);
  await check('saved avatar and banner render as decoded images',`document.querySelector('#imageFixture .profile-portrait img').getBoundingClientRect().width>0`);
  await evaluate(`document.querySelector('#imageFixture').remove()`);
  assert.deepEqual(exceptions,[]);report.checks.push('no uncaught browser errors');
  writeFileSync(path.join(output,'report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
}finally{socket?.close();browser.kill();}
